# 导航菜单配置，键为菜单名称，值为对应页面路径或链接
menu:
  Home: /           # 主页链接
  Archives: /archives  # 文章归档页链接
  Tags: /tags       # 标签页链接
  About: /about     # 关于页链接
  RSS: /sitemap.xml # RSS 或站点地图链接

# 作者信息配置
author: zhiqiang               # 博客作者名称
email: zhiqiang2033@gmail.com # 联系邮箱
address: 中国                  # 地址信息（显示在联系方式处）

# 统计服务配置（默认注释，需要启用时取消注释并填写对应ID）
# baidu_analytics_id: YOUR_BAIDU_ID    # 百度统计ID
# google_analytics_id: YOUR_GOOGLE_ID  # Google Analytics ID
# clarity_analytics_id: YOUR_CLARITY_ID # Microsoft Clarity ID

# 友情链接列表，每个元素包含友链名称和对应链接
friends:
  - name: CNB                     # 友链名称
    url: https://cnb.cool/zhiqiangwang  # 友链网址
  - name: GitHub
    url: https://github.com/chihqiang
  - name: 志强vlog
    url: https://www.zhiqiang.wang

# sitemap 配置，控制站点地图生成参数
sitemap:
  path:
    - sitemap.xml    # 生成的 sitemap 文件名，支持数组
  rel: false          # 是否在页面中添加 <link rel="sitemap"> 标签，false 表示不添加
  tags: true          # 是否在 sitemap 中包含标签页，true 为包含
  categories: true    # 是否在 sitemap 中包含分类页，true 为包含
